### ISSUE TITLE
AP ÖREB-Datenbank

### ISSUE THREAD

**Issue by edigonzales** [sogis-oereb/oereb-db#1]
### Inhalt

- Neue Strukturierung (Schema anlegen mit neuem Rahmenmodell, Daten der amtlichen Vermessung, (AV), PLZ, WMS (Views))
- Grundbuchkreise sind neu im Rahmenmodell Konfiguration erfasst
- «so_g_v_0180822nachfuehrngskrise_gemeinde» und «so_g_v_0180822grundbuchkreise_grundbuchkreis» wahrscheinlich nicht mehr nötig.

### Input

- Bestehenden Datenstruktur 

### Output

- Docker Image 
- Shellskript

### Tasks

- [x] DDL für WMS-Tabellen (Datenumbau in GRETL-Jobs)
- [x] DDL für GDI-DB
- [x] "transfer_XXX.sql" -> "transfer_XXX_gdi.sql"
- [x] transfer_XXX.sql: Bei den GRANTS müssen Platzhalter drinstehen, keine Namen. Siehe V1_0. 
- [x] QGS-Projekt (non-dummy)
- [ ] Bei WMS-Tabellen Index auf ArtCode?
